language: c

compiler:
- gcc

before_script:
- git clone https://github.com/rumpkernel/buildrump.sh

script:
- ./buildrump.sh/buildrump.sh -q -T rumptools
- ./rumptools/rumpmake

notifications:
  irc:
    channels:
      - "chat.freenode.net#rumpkernel-builds"
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    skip_join: true
    use_notice: true
  email:
    recipients:
      - rumpkernel-builds@lists.sourceforge.net
    on_success: always
    on_failure: always
